spring:
  cloud:
    gcp:
      project-id: testerproject
      pubsub:
        emulator-host: localhost:8085
      # if the emulator-host property is not set or set to empty string, the emulator wont be used but the real Pub/Sub service
      # more info https://cloud.google.com/pubsub/docs/publish-receive-messages-client-library


# pubsub:
#   subscription.name: aGivenSubscription
#   topic.name: aGivenTopic
